src/CarWorkshopMVC/Models/About.cs
namespace CarWorkshopMVC.Models
{
    public class About
    {
        public int ID { get; set; } 
        public string? Title { get; set; }
        public string? Description { get; set; }
        public List<string>? Tags { get; set; } = new List<string>();
    }
}

src/CarWorkshopMVC/Models/ErrorViewModel.cs
namespace CarWorkshopMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/CarWorkshopMVC/Controllers/CarWorkshopController.cs
using Microsoft.AspNetCore.Mvc;
using CarWorkshop.Domain.Entities;
using CarWorkshop.Domain.Interfaces;
using CarWorkshop.Application.CarWorkshop;
using Microsoft.AspNetCore.Mvc.Formatters;
using FluentValidation;
using MediatR;
using CarWorkshop.Application.CarWorkshop.Queries.GetAllCarWorkshop;
using CarWorkshop.Application.CarWorkshop.Commands.CreateCarWorkShop;
using CarWorkshop.Application.CarWorkshop.Queries.GetCarWorkshopByEncodedName;
using CarWorkshop.Application.CarWorkshop.Commands.EditCarWorkShop;

namespace CarWorkshopMVC.Controllers
{
    public class CarWorkshopController : Controller
    {
        private readonly IMediator _mediator;

        public CarWorkshopController(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task<IActionResult> Index()
        {
            var carWorkshopList = await _mediator.Send(new GetAllCarWorkshopQuery());
            return View(carWorkshopList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateCarWorkshopCommand command)
        {
            if (!ModelState.IsValid)
            {
                return View(command);
            }
            await _mediator.Send(command);
            return RedirectToAction(nameof(Index));
        }

        [Route("CarWorkshop/{encodedName}/Details")]
        public async Task<IActionResult> Details(string encodedName)
        {
            var carWorkshopDto = await _mediator.Send(new GetCarWorkshopByEncodedNameQuery(encodedName));
            return View(carWorkshopDto);
        }

        [Route("CarWorkshop/{encodedName}/Edit")]
        public async Task<IActionResult> Edit(string encodedName)
        {
            var carWorkshopDto = await _mediator.Send(new GetCarWorkshopByEncodedNameQuery(encodedName));
            return View(carWorkshopDto);
        }

        [HttpPost]
        [Route("CarWorkshop/{encodedName}/Edit")]
        public async Task<IActionResult> Edit(EditCarWorkshopCommand command)
        {
            if (!ModelState.IsValid)
            {
                return View(command);
            }
            await _mediator.Send(command);
            return RedirectToAction(nameof(Index));
        }
    }
}

src/CarWorkshopMVC/Controllers/HomeController.cs
using CarWorkshopMVC.Models;
using CarWorkshopMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CarWorkshopMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult About() {

            List<About> model = new List<About>
            {
                new About()
                {
                    ID = 1,
                    Title = "Test1",
                    Description = "TestTest1",
                    Tags = new List<string> {"tag11", "tag12", "tag13"}
                },
                new About()
                {
                    ID = 2,
                    Title = "Test2",
                    Description = "TestTest2",
                    Tags = new List<string> {"tag21", "tag22", "tag23"}
                }
            };

            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/CarWorkshopMVC/Views/CarWorkshop/Create.cshtml
@using CarWorkshop.Application.CarWorkshop.Commands.CreateCarWorkShop;

@model CreateCarWorkshopCommand

<h1>Car Workshop Create</h1>
<p>:)</p>

<hr/>

<div class="row">
    <div class="col-md-4">
        <form action="/CarWorkshop/Create" method="post">
            <div class="form-group mb-3">
                <label class="control-label" asp-for="Name">Name</label>
                <input class="form-control" type="text" asp-for="Name" />
                <span asp-validation-for="Name"  class="text-danger" />
                @Html.ValidationMessageFor(model => model.Name)
            </div>
            <div class="form-group mb-3">
                <label class="control-label" asp-for="Description">Description</label>
                <input class="form-control" type="text" asp-for="Description" />
                <span asp-validation-for="Description" class="text-danger" />
            </div>
            <div class="form-group mb-3">
                <label class="control-label" asp-for="About">About</label>
                <input class="form-control" type="text" asp-for="About" />
                <span asp-validation-for="About" class="text-danger" />
            </div>
            <div class="form-group mb-3">
                <label class="control-label" asp-for="PhoneNumber">PhoneNumber</label>
                <input class="form-control" type="text" asp-for="PhoneNumber" />
                <span asp-validation-for="PhoneNumber" class="text-danger" />
            </div>
            <div class="form-group mb-3">
                <label class="control-label" asp-for="Street">Street</label>
                <input class="form-control" type="text" asp-for="Street" />
                <span asp-validation-for="Street" class="text-danger" />
            </div>
            <div class="form-group mb-3">
                <label class="control-label" asp-for="City">City</label>
                <input class="form-control" type="text" asp-for="City" />
                <span asp-validation-for="City" class="text-danger" />
            </div>
            <div class="form-group mb-3">
                <label class="control-label" asp-for="PostalCode">PostalCode</label>
                <input class="form-control" type="text" asp-for="PostalCode" />
                <span asp-validation-for="PostalCode" class="text-danger" />
            </div>
            <div class="form-group mb-3">
                <input class="btn btn-primary" type="submit" value="Create"/>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/CarWorkshopMVC/Views/CarWorkshop/Details.cshtml
@model CarWorkshop.Application.CarWorkshop.CarWorkshopDto

@{
    ViewData["Title"] = "Details";
}

<h1>@Model.Name - Details</h1>

<div>
    <h4>CarWorkshopDto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.About)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.About)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { encodedName = Model.EncodedName }) |
    <a asp-action="Index">Back to List</a>
</div>

src/CarWorkshopMVC/Views/CarWorkshop/Edit.cshtml
@model CarWorkshop.Application.CarWorkshop.CarWorkshopDto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CarWorkshopDto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="About" class="control-label"></label>
                <input asp-for="About" class="form-control" />
                <span asp-validation-for="About" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/CarWorkshopMVC/Views/CarWorkshop/Index.cshtml
@model IEnumerable<CarWorkshop.Application.CarWorkshop.CarWorkshopDto>

@{
    ViewData["Title"] = "Car Workshop";
}

<h1>Car Workshop</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-secondary">Create New</a>
</p>

<div class="row">
    @foreach (var item in Model)
    {
        <div class="card m-3" style="width:18rem">
            <div class="card-body">
                <h5 class="card-title">@item.Name</h5>
                <h6 class="card-subtitle mb-2 text-muted">@item.PhoneNumber</h6>
                <p class="card-text">@item.Description</p>
                <a class="btn btn-primary" 
                    asp-action="Details" asp-controller="CarWorkshop"
                    asp-route-encodedName="@item.EncodedName">Details</a>
                <a class="btn btn-outline-secondary"
                   asp-action="Edit" asp-controller="CarWorkshop" 
                   asp-route-encodedName="@item.EncodedName">Edit</a>
            </div>
        </div>
    }
</div>

src/CarWorkshopMVC/Views/Home/About.cshtml
@model IEnumerable<CarWorkshopMVC.Models.About>

@{
    ViewData["Title"] = "About";
}

<h1>About</h1>

<p>
    <a asp-action="Create" asp-controller="CarWorkshop">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tags)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @foreach(var tag in item.Tags)
                {
                    <p>@tag</p>
                }
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

src/CarWorkshopMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/CarWorkshopMVC/Views/Shared/_Layout.cshtml
@{
    var urlControlAction = ViewContext.RouteData.Values["Action"]?.ToString();
    var urlControlController = ViewContext.RouteData.Values["Controller"]?.ToString();
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarWorkshop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarWorkshopMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CarWorkshop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark @(urlControlController == "Home" && urlControlAction == "Index" ? "active" : "")" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark @(urlControlController == "Home" && urlControlAction == "Privacy" ? "active" : "")" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark @(urlControlController == "Home" && urlControlAction == "About" ? "active" : "")" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark @(urlControlController == "CarWorkshop" && urlControlAction == "Index" ? "active" : "")" asp-area="" asp-controller="CarWorkshop" asp-action="Index">Car Workshop</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CarWorkshop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>